//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string Contact { get; set; }
        public string EmailID { get; set; }
        public string Languagee { get; set; }
    }
}
